state_names = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

misc_abbreviation = {
    'nw': 'North West',
    'sw': 'South West',
    'rd': 'Road',
    'ne': 'North East',
    'st': 'Street',
    'pkwy': 'Parkway',
    'dr': 'Drive',
    'ln': 'Lane',
}

us_state_capitals = {
    "alabama": "montgomery",
    "alaska": "juneau",
    "arizona": "phoenix",
    "arkansas": "little rock",
    "california": "sacramento",
    "colorado": "denver",
    "connecticut": "hartford",
    "delaware": "dover",
    "florida": "tallahassee",
    "georgia": "atlanta",
    "hawaii": "honolulu",
    "idaho": "boise",
    "illinois": "springfield",
    "indiana": "indianapolis",
    "iowa": "des moines",
    "kansas": "topeka",
    "kentucky": "frankfort",
    "louisiana": "baton rouge",
    "maine": "augusta",
    "maryland": "annapolis",
    "massachusetts": "boston",
    "michigan": "lansing",
    "minnesota": "saint paul",
    "mississippi": "jackson",
    "missouri": "jefferson city",
    "montana": "helena",
    "nebraska": "lincoln",
    "nevada": "carson city",
    "new hampshire": "concord",
    "new jersey": "trenton",
    "new mexico": "santa fe",
    "new york": "albany",
    "north carolina": "raleigh",
    "north dakota": "bismarck",
    "ohio": "columbus",
    "oklahoma": "oklahoma city",
    "oregon": "salem",
    "pennsylvania": "harrisburg",
    "rhode island": "providence",
    "south carolina": "columbia",
    "south dakota": "pierre",
    "tennessee": "nashville",
    "texas": "austin",
    "utah": "salt lake city",
    "vermont": "montpelier",
    "virginia": "richmond",
    "washington": "olympia",
    "west virginia": "charleston",
    "wisconsin": "madison",
    "wyoming": "cheyenne"
}