state_names = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

misc_abbreviation = {
    "north west": "nw",
    "south west": "sw",
    "road": "rd",
    "north east": "ne",
    "street": "st",
    "parkway": "pkwy",
    "drive": "dr",
    "lane": "ln",
    "avenue": "ave",
}

us_state_capitals = {
    "alabama": "montgomery",
    "alaska": "juneau",
    "arizona": "phoenix",
    "arkansas": "little rock",
    "california": "sacramento",
    "colorado": "denver",
    "connecticut": "hartford",
    "delaware": "dover",
    "florida": "tallahassee",
    "georgia": "atlanta",
    "hawaii": "honolulu",
    "idaho": "boise",
    "illinois": "springfield",
    "indiana": "indianapolis",
    "iowa": "des moines",
    "kansas": "topeka",
    "kentucky": "frankfort",
    "louisiana": "baton rouge",
    "maine": "augusta",
    "maryland": "annapolis",
    "massachusetts": "boston",
    "michigan": "lansing",
    "minnesota": "saint paul",
    "mississippi": "jackson",
    "missouri": "jefferson city",
    "montana": "helena",
    "nebraska": "lincoln",
    "nevada": "carson city",
    "new hampshire": "concord",
    "new jersey": "trenton",
    "new mexico": "santa fe",
    "new york": "albany",
    "north carolina": "raleigh",
    "north dakota": "bismarck",
    "ohio": "columbus",
    "oklahoma": "oklahoma city",
    "oregon": "salem",
    "pennsylvania": "harrisburg",
    "rhode island": "providence",
    "south carolina": "columbia",
    "south dakota": "pierre",
    "tennessee": "nashville",
    "texas": "austin",
    "utah": "salt lake city",
    "vermont": "montpelier",
    "virginia": "richmond",
    "washington": "olympia",
    "west virginia": "charleston",
    "wisconsin": "madison",
    "wyoming": "cheyenne",
}
